### ISSUE TITLE
How to track poposals and votes

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/foundation#11]
Things to track - 
- new proposals at every validated network
- upgrade dates (with possibility to remind 1-2 days before)
- status of Bro vote for every prop

Possible ways of realization: 
Grafana: 
   
    + create separate board, pull automatically info from nodes about new prop appear (with some data, eg vote start, end,) 
    - how to track actual vote 
   
Github: 

    + separate board\repo with issues 
     - lots of manual work, how to remind of upcoming deadlines?
 
Calendar (aka Google calendar):

    + easy reminding, easy tracking 
    - manual filling

**Comment by bro-n-bro-0** [comment]
Check this 

https://kalpatech.co/alerts

**Comment by altbro** [comment]
Deployed the bot on postgres-hasura node. 
Tracking performance
