### ISSUE TITLE
Create bro t-shirts 

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/foundation#15]
Design and print 10 t-shirts with bro logo. 
Black color, with white logo 
Possibly big logo on the back, small on the front left side 
Possibly add some kind of slogan to the back : 
- While Big brother wathing you, bro - validate for you 
- Your trusted validator
- Let us validate 
etc.

**Comment by CyberObiOne** [comment]
One more possible slogan: Eat, Sleep, Stake - Repeat.

**Comment by bro-n-bro-0** [comment]
Also stickers
