### ISSUE TITLE
Microtick shut down post

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/foundation#24]
According to [that proposal](https://microtick.ezstaking.io/proposals/20), Microtick network is migrating to eth network

We want to shut down our validator nodes as soon as DiscoveryDEX validator is created

Please notify about that all our Micro delegators. Use quotes and refs from the named proposal.

**Comment by bro-n-bro-99** [comment]
info posted in tw, tg, cyber blog
