### ISSUE TITLE
Cosmos forum/ eco stake validator description

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#31]
Create description of Bro validator 
https://forum.cosmos.network/c/start-here/validator-profiles/33

Example profile: https://cosmosvalidators.org/ecostake
Validator Registry data: https://github.com/eco-stake/validator-registry/tree/master/ecostake

**Comment by bro-n-bro-99** [comment]
validator description is ready, the only missing part is "Our Infrastructure" section - @altbro informed, awaiting for his response

**Comment by bro-n-bro-99** [comment]
FYI - for some reason cosmosvalidators.org is down

**Comment by altbro** [comment]
Bro infrastructure

We maintain a precise approach to our infrastructural setup. Most of the nodes run on bare-metal servers distributed in several locations. We do run several (at least 2) nodes per every network, which allows us to use sentry architecture. 
Recently we started migration to our own infrastructure and own servers to improve distribution and raise protection against political/human factors which recently becoming more and more serious threat for node operators. Every our node is secured, redundant and monitored to keep highest uptime ratio in every chain we support.
