### ISSUE TITLE
Create snapshot for Omniflix welcome NFT

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#32]
Please, create snapshot for all delegators splitting by wallet accounts, the same as for Bro Wednesday.
Snapshot date is 1 September. 
Cut all zero accounts, amount is less than 1 $
Exclude Omniflix.

Bostrom height : 4448000
https://www.mintscan.io/cosmos/blocks/11884000
https://www.mintscan.io/crescent/blocks/2146000
https://www.mintscan.io/desmos/blocks/4983000
https://www.mintscan.io/emoney/blocks/1288000
https://www.mintscan.io/evmos/blocks/3745000
https://www.mintscan.io/gravity-bridge/blocks/3537000
https://www.mintscan.io/juno/blocks/4619000
https://www.mintscan.io/osmosis/blocks/5835000
https://www.mintscan.io/stargaze/blocks/4475000

**Comment by altbro** [comment]
Osmosis snap
https://rpc.bronbro.io/exports/osmosis_5835000.tar.gz
