### ISSUE TITLE
Create thread on cosmos hub forum/ commonwealth/reddit/twitter about Stride atom distributions

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#37]
@bro-n-bro-99 , please, create a post about Stride atom distribution.
Theses: 
1. Why decentralization is important. Current voting power.
2. Current Stride distribution 
3. What we suggest:
- distribute tokens ONLY between validators who validate Cosmos Hub and Stride

--
Distribution:
To improve decentralization there are some options:
1.  Leave as it
2.  From lower voting power in Cosmos Hub to higher
3. Math formula that will calculate voting power in Cosmos Hub and Stride and take average between them.
4. Your suggestion here.

**Comment by bro-n-bro-99** [comment]
https://forum.cosmos.network/t/proposal-adjustments-to-the-stride-teams-atom-distribution-program/8162/6
