### ISSUE TITLE
Blog in bostrom (quitter)

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/foundation#4]

**Comment by bro-n-bro-99** [comment]
acc created, the process showed

**Comment by altbro** [comment]
Post created 
https://cyb.ai/network/bostrom/contract/bostrom1ydc5fy9fjdygvgw36u49yj39fr67pd9mv67ety

**Comment by altbro** [comment]
@bro-n-bro-99 posted to channels, could be closed
