### ISSUE TITLE
Update validator description with bro apps

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/foundation#44]
@bro-n-bro-99 please create new description draft, to include : app,  rating (maybe specific link for every chain ) links, etc.

@altbro update description

**Comment by bro-n-bro-99** [comment]
Bare metal interchain relayer and validator with a range of web tools and services, dedicated to ensuring the integrity and decentralization of the blockchain. Access our tools app.bronbro.io for effective portfolio management and score.bronbro.io (in BETA) to compare validators based on key metrics.

**Comment by altbro** [comment]
* community driven validator

**Comment by bro-n-bro-99** [comment]
@altbro 
Bare metal interchain relayer and community driven validator with a range of web tools and services, ensuring the decentralization of the blockchain. Access our tools app.bronbro.io for effective portfolio management and score.bronbro.io (in BETA) to compare validators based on key metrics.

**Comment by altbro** [comment]
updated
