### ISSUE TITLE
Create bro info (Readme file)

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#49]
![image](https://github.com/bro-n-bro/foundation/assets/89855562/e880973b-4176-4b1c-b920-2e93a2f60bbf)

Possible text:

Who Are We?
Bro_n_Bro foundation began in early 2021 as a Validator for the Cosmos Ecosystem. Shortly after joining and understanding the core and fundamental values of the ecosystem, we started relaying and expanding other services to networks and projects.
Our mission is simple: to support and develop a decentralized world. We maintain the highest standards for security and performance as well as providing the most accurate data to our community.
Our team consists of experienced engineers and analysts, creative marketers and talented designers all over the world. Bro_n_Bro is trusted by thousands of stakers. We build for decentralization until it is achieved.

Validated Networks
Right now we validate on 12 chains (the number is constantly growing).
We support autocompounding on all chains we validate. 

Our Contributions:
Bro App for easier managing #Cosmos assets: https://app.bronbro.io/
TG and Discord stat bots
Validator ratings: https://score.bronbro.io/
Monitor boards: https://monitor.bronbro.io/
IBC relaying
Validator Proposal bot: https://github.com/bro-n-bro/bro-proposals-tracking-bot
Open source indexer for Cosmos ecosytem (in the development)

IBC Relaying
To support the blockchain communities, we also run IBC relayers for the Cosmos ecosystem at our own expense.

Our Infrastructure
We take a precision approach to our infrastructure setup. Most of the nodes run on bare-metal servers distributed in several locations. 

Active on-chain Governance
We are actively involved in governance, as this is key to the progress of every network. We always take into account what is best for both the network and the community, engaging on Twitter and TG group to discuss our decisions with our delegators, letting them know that they can change their vote if they disagree.

Website: https://bronbro.io/
Twitter: https://twitter.com/Bro_n_Bro
Github: https://github.com/bro-n-bro
TG group: https://t.me/bro_n_bro_community
Reddit: https://www.reddit.com/user/bro_n_bro

**Comment by bro-n-bro-99** [comment]
https://github.com/bro-n-bro-99/.github/blob/main/README.md
