### ISSUE TITLE
Reimburse lost tokens for bro_n_bro bostrom delegators

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/foundation#50]
1. Find the burned tokens amount @bro-n-bro-0 
2. Calculate the shares from the snapshot @iljagrabar14 
3. Calculate the amount of the tokens to reimburse @bro-n-bro-0 @iljagrabar14 
4. Generate the multisend transaction for the payment @bro-n-bro-0 
5. Send the transaction @altbro 
6. Follow each step with posts @bro-n-bro-99

**Comment by bro-n-bro-0** [comment]
Burned tokens amount is 1516573400 boot

**Comment by iljagrabar14** [comment]
csv file
Del address ; (shares/sum(shares))  * burned_token ; (amount/sum(amount))  * burned_token 
from json file

**Comment by bro-n-bro-0** [comment]
https://cyb.ai/network/bostrom/tx/0909CFD72B877A45509BE8CD378562F95C379A9D7EA848229DCB2C3DDE2765DD
