### ISSUE TITLE
Celestia delegation form

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#66]
https://blog.celestia.org/validator-delegation-program/

Hello everyone, regarding the delegation program - we are noticing some are not following instructions correctly, so pointing out a few things here:

CAREFULLY read the whole delegation program page in our docs
make sure you cover all the eligibility criteria, certain submissions do not adhere to them
active validator means that your validator is in the active set
make sure you answer questions in the form like we ask, it is very specific in what we want from you

**Comment by bro-n-bro-99** [comment]
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzl2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18579097a9f17fb656ee471a2fdf9d43428c129a/Screenshot%202024-02-19%20at%2021.49.30.png" alt="Screenshot 2024-02-19 at 21.49.30.png" />
