### ISSUE TITLE
Claim profile on stakingrewards.com

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#67]
https://www.stakingrewards.com/providers/all?sort=assets_under_management&timeframe=30d&order=desc&byChange=false&verifiedFirst=false

**Comment by bro-n-bro-99** [comment]
<img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--301be58758af28438ac84025e2f10ce7615e7098/Screenshot%202024-02-15%20at%2015.13.20.png" alt="Screenshot 2024-02-15 at 15.13.20.png" />
