### ISSUE TITLE
Create templates for restake

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#68]
https://pbs.twimg.com/media/GF15MgUXYAITcYo?format=jpg&name=large
https://pbs.twimg.com/media/GFvwQaaWYAAbVdR?format=jpg&name=large

**Comment by bro-n-bro-99** [comment]
https://bronbro.notion.site/How-to-Auto-Compound-your-BAND-Staking-Rewards-with-Bro_n_Bro-c436eea923aa4cea9a682c63e742e94e?pvs=4
