### ISSUE TITLE
Create template for guides

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/foundation#69]
https://miro.medium.com/v2/resize:fit:1400/format:webp/1*zPmfjKrXb7DVrb68NvFDvw.jpeg

**Comment by bro-n-bro-99** [comment]
https://bronbro.notion.site/How-to-Stake-BAND-Band-Protocol-d3dbd3524d7d4fd1aa408f8391fe97f8?pvs=4
