### ISSUE TITLE
VAL Names cleanup

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/foundation#83]
Change names to Please redelegate
- Juno 
- desmos

Change names only 
archway 
crescent
akash

**Comment by bro-n-bro-0** [comment]
https://www.mintscan.io/akash/validators/akashvaloper102m9y6tnfndg262vc8uyktpd6wgr6fpzlw6z2k
https://www.mintscan.io/archway/validators/archwayvaloper18pvdnnuax3nesemjhnv5vt9dpx0l9qq5gsn3j7
https://www.mintscan.io/juno/validators/junovaloper1quqxfrxkycr0uzt4yk0d57tcq3zk7srm7sm6r8
